MCSC-961 Scheme Credit Consent Content
hmrc/submit-public-pension-adjustment-frontend pull request #145
Opened 2024-07-09 14:11 UTC by TJSarno

2024-07-12 08:46 UTC, MichaelAAbbott requested changes

2024-07-12 08:46 UTC, MichaelAAbbott commented on app/models/SchemeCreditConsent.scala
> +  def saveConsent(userAnswers: UserAnswers, boolean: Boolean): UserAnswers =
Delete this method, it is not used anywhere

2024-07-12 08:46 UTC, MichaelAAbbott commented on conf/messages.en
Welsh place holders please :)

2024-07-12 08:46 UTC, MichaelAAbbott commented on test/controllers/SchemeCreditConsentControllerSpec.scala
Needs unit tests to check the user answer is being set

2024-07-12 08:46 UTC, MichaelAAbbott commented on test/controllers/SchemeCreditConsentControllerSpec.scala
Also needs unit tests to check for redirection to the next page

2024-07-17 08:27 UTC, bharti5verma approved these changes

2024-07-17 10:30 UTC, closed without merging