MCSC-653
hmrc/submit-public-pension-adjustment-frontend pull request #78
Opened 2023-11-13 15:30 UTC by TJSarno

2023-11-14 10:46 UTC, MichaelAAbbott submitted a review, later dismissed
Amazing, great stuff! :+1:

2023-11-14 10:47 UTC, ElliotAndersonHMRC commented on conf/messages.en
> +cannotUseServiceNotIndividual.title = Cannot use submission service - Calculate your public service pension adjustment - GOV.UK
"- Calculate your public service pension adjustment - GOV.UK" should be removed as this is automatically added to the end of the title

2023-11-14 10:47 UTC, ElliotAndersonHMRC requested changes
One small fix

2023-11-14 11:08 UTC, ElliotAndersonHMRC submitted a review, later dismissed
Looks good!

2023-11-29 15:54 UTC, dacohm commented on app/views/UnauthorisedView.scala.html
> +    showSignOut = false
We still want a sign out link since there is a need to sign out from GG.

2023-11-29 16:27 UTC, dacohm approved these changes

2023-11-29 16:56 UTC, merged