MCSC 343 Create Scheme Pays Debit Pages
hmrc/submit-public-pension-adjustment-frontend pull request #8
Opened 2023-07-14 14:15 UTC by bharti5verma

2023-07-14 15:43 UTC, MichaelAAbbott requested changes

2023-07-14 15:43 UTC, MichaelAAbbott commented on test-utils/generators/Generators.scala
Should this be a randomly generated valid PSTR rather than a fixed valid PSTR?

2023-07-17 09:25 UTC, bharti5verma commented on test-utils/generators/Generators.scala
Fixed

2023-07-17 09:26 UTC, MichaelAAbbott approved these changes
LG2M!

2023-07-17 09:37 UTC, merged